// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp-N9Qv-hns_G89tMc4xpKaCnxLgY8yYw',
    appId: '1:789049377236:web:09a3ca6859876f443ad641',
    messagingSenderId: '789049377236',
    projectId: 'el-cuaderno-de-mario',
    authDomain: 'el-cuaderno-de-mario.firebaseapp.com',
    storageBucket: 'el-cuaderno-de-mario.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN9hsrqFmOv5bVcI6YZ2zpGn3xuv1Mag8',
    appId: '1:789049377236:android:1b91e1ad70c22e623ad641',
    messagingSenderId: '789049377236',
    projectId: 'el-cuaderno-de-mario',
    storageBucket: 'el-cuaderno-de-mario.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRFHZXAz3FB1PSCumk3u6wvc11BbKoYCw',
    appId: '1:789049377236:ios:24a4a2c707d5d0073ad641',
    messagingSenderId: '789049377236',
    projectId: 'el-cuaderno-de-mario',
    storageBucket: 'el-cuaderno-de-mario.firebasestorage.app',
    iosBundleId: 'com.elcuadernodemario.elCuadernoDeMario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp-N9Qv-hns_G89tMc4xpKaCnxLgY8yYw',
    appId: '1:789049377236:web:229f90b95af481543ad641',
    messagingSenderId: '789049377236',
    projectId: 'el-cuaderno-de-mario',
    authDomain: 'el-cuaderno-de-mario.firebaseapp.com',
    storageBucket: 'el-cuaderno-de-mario.firebasestorage.app',
  );
}
